name: dating_now
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Core
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  get_it: ^7.2.0

  # UI
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0
  card_swiper: ^2.0.4

  # NETWORK
  dio: ^4.0.6
  pretty_dio_logger: ^1.2.0-beta-1
  dart_ipify: ^1.1.1
  connectivity_plus: ^3.0.2

  # STORAGE
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^7.0.1

  # NOTIFICATION
  flutter_local_notifications: ^13.0.0

  # FIREBASE
  firebase_core: ^1.17.1
  firebase_dynamic_links: ^4.2.5
  firebase_messaging: ^11.4.1

  # UTIL
  json_serializable: ^6.5.4
  equatable: ^2.0.5
  permission_handler: ^10.2.0
  intl: ^0.17.0
  device_info_plus: ^8.0.0
  package_info_plus: ^3.0.2
  logger: ^1.1.0
  sizer: ^2.0.15
  flutter_screenutil: ^5.6.0
  fluttertoast: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  json_annotation: ^4.7.0
  flutter_gen_runner: ^5.1.0+1
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Sk-Modernist
      fonts:
        - asset: assets/fonts/Sk-Modernist-Bold.otf
          weight: 700
        - asset: assets/fonts/Sk-Modernist-Regular.otf
          weight: 400
        - asset: assets/fonts/Sk-Modernist-Mono.otf

flutter_gen:
  output: lib/src/core/gen/
  integrations:
    flutter_svg: true
    flare_flutter: false

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/ic_launcher.png"
#  adaptive_icon_background: "#ffffff" #"#ec407a"
#  adaptive_icon_foreground: "assets/ic_launcher_light.png"
