name: ekyc_flutter_sdk
description: A new flutter plugin project.
version: 0.0.1
homepage: https://github.com/Techainer

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  tflite_flutter: ^0.9.0
  tflite_flutter_helper: ^0.2.1
  image: ^3.0.2
#  camera:
#    git:
#      url: https://github.com/Techainer/flutter-plugins.git
#      ref: fix_iphone6_crashapp
#      path: packages/camera/camera


  camera:
#    path: /Users/hieunt/ekycSDK/FlutterDev/flutter-plugins/packages/camera/camera
#    path: /Volumes/Savis/HDSaiSon/sources/mobile-app/sdk_ekyc/flutter-plugins/packages/camera/camera
    path: ../flutter-plugins/packages/camera/camera

  scidart: ^0.0.2-dev.9
  # sort_flutter:
  #   git:
  #     url: https://github.com/HieuNT1998/sort_flutter.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.example.ekyc_flutter_sdk
        pluginClass: EkycFlutterSdkPlugin
      ios:
        pluginClass: EkycFlutterSdkPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - packages/ekyc_flutter_sdk/assets/models/face_detection_back.tflite
    - packages/ekyc_flutter_sdk/assets/models/face_detection_front.tflite
    - packages/ekyc_flutter_sdk/assets/models/Faceliveness_mobilenetv2_0.25_mymodel_3_train_01042022_export_01042022.tflite
    - packages/ekyc_flutter_sdk/assets/models/cardliveness_mymodel_12_mobilenetv2_26classes_finger_spotlight_04042022_1553.tflite

  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
