// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0ScRke93Fbd1IQIujz6dxAo28NbZATVE',
    appId: '1:1082247271513:web:058d9cee25156d1cadcd48',
    messagingSenderId: '1082247271513',
    projectId: 'fcm-bge',
    authDomain: 'fcm-bge.firebaseapp.com',
    storageBucket: 'fcm-bge.appspot.com',
    measurementId: 'G-2NN9WK5CRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdVXBm-4Lu2G20uME-LZA44Nzl9OsHZx4',
    appId: '1:1082247271513:android:1304964baa3d0af3adcd48',
    messagingSenderId: '1082247271513',
    projectId: 'fcm-bge',
    storageBucket: 'fcm-bge.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD11Cfwzyz8ej34Gv9Bhc3kT-dYR7F7EhA',
    appId: '1:1082247271513:ios:61e7d6867d95a376adcd48',
    messagingSenderId: '1082247271513',
    projectId: 'fcm-bge',
    storageBucket: 'fcm-bge.appspot.com',
    iosClientId: '1082247271513-4lh2ki3j1tb22gu2ql7p3b6t1t01jg3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseCloudMessage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD11Cfwzyz8ej34Gv9Bhc3kT-dYR7F7EhA',
    appId: '1:1082247271513:ios:61e7d6867d95a376adcd48',
    messagingSenderId: '1082247271513',
    projectId: 'fcm-bge',
    storageBucket: 'fcm-bge.appspot.com',
    iosClientId: '1082247271513-4lh2ki3j1tb22gu2ql7p3b6t1t01jg3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseCloudMessage',
  );
}
