name: spam_sms

publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.2
  permission_handler: ^10.2.0
  file_picker: ^5.3.2
  device_info_plus: ^9.0.2
  excel: ^2.1.0
  flutter_svg: ^2.0.6
  flutter_sms:
    path: flutter_sms

  # Statement Manager
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Analysis Code
  flutter_lints: ^2.0.1
  dart_code_metrics: ^5.7.2

  # Logger
  logger: ^1.3.0

  # Gen
  build_runner: ^2.4.4
  flutter_gen_runner: ^5.3.1
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1

flutter_gen:
  output: lib/core/theme/gen/
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: true
    lottie: true
#  colors:
#    inputs:
#      - assets/color/colors.xml
#    outputs:
#      class_name: VTVColor

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/img_launcher_icon.png"

# flutter_native_splash-production.yaml
flutter_native_splash:
  color: "#000000"
  image: assets/images/img_splash_icon.png

#  android_12:
#    image: assets/images/img_splash_icon.png
#    icon_background_color: "#000000"

  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
